apiVersion: v1
kind: Service
metadata:
  name: bookapp
spec:
  type: LoadBalancer
  selector:
    app: bookapp
  ports:
    - port: 8888
      protocol: "TCP"
      targetPort: 8088
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookapp
spec:
  selector:
    matchLabels:
      app: bookapp
  template:
    metadata:
      labels:
        app: bookapp
    spec:
      containers:
        - name: bookapp
          image: book-server:latest
          imagePullPolicy: Never
          env:
            - name: BOOK_SER_PORT
              value: "8088"
